---
- name: Add repo
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ apt_repo }}"
  become: yes
  notify: Update apt-cache
  tags:
    - packages

- name: Add keys
  apt_key:
    keyserver: "{{ item.keyserver | default(omit) }}"
    id: "{{ item.key | default(omit) }}"
    url: "{{ item.url | default(omit) }}"
  with_items: "{{ gpg_keys }}"
  become: yes
  notify: Update apt-cache

- name: Flush handlers
  meta: flush_handlers

- name: Install packages
  apt:
    name: "{{ item }}"
    allow_unauthenticated: yes
    state: present
  with_items: "{{ apt_packages }}"
  become: yes
  tags:
    - packages

- name: Install sublime_remote
  get_url:
    url: https://raw.github.com/aurora/rmate/master/rmate
    dest: /usr/local/bin/subl
    mode: 0755
  become: yes
  when: sublime_remote
  tags:
    - sublime

- name: Process templates
  template:
    src: "{{ item.template }}"
    dest: "{{ item.dest }}"
  become: yes
  with_items: "{{ template_files_config }}"
  register: templates_config
  tags:
    - configs

- name: Create directories
  file:
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
    owner: "{{ item.owner | default(omit) }}"
    path: "{{ item.path }}"
    recurse: "{{ item.recurse | default('no') }}"
    state: "{{ item.state | default('file') }}"
  with_items: "{{ create_directories }}"
  become: yes
