---
- name: "Install dependencies"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    - vim
  tags:
    - docker_install
  become: true

- name: "Define release variable in task"
  shell: . /etc/os-release; echo "$ID"
  register: url
  tags:
    - docker_install

- name: "Add Dockers official GPG key"
  apt_key:
    url: https://download.docker.com/linux/{{ url.stdout }}/gpg
    state: present
  become: true
  tags:
    - docker_install

- name: "Add Docker’s repository"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ url.stdout }} {{ ansible_distribution_release }} stable
    state: present
  become: true
  tags:
    - docker_install

- name: "Install docker"
  apt:
    name: docker-ce
    state: present
  become: true
  tags:
    - docker_install

- name: "Add user to docker group"
  user:
    name: "{{ vagrant_remote_user }}"
    groups: docker
    append: yes
  become: true
  tags:
    - docker_install

- name: 'Install pip'
  apt:
    name: python-pip
    state: present
  become: true
  tags:
    - docker_install
    - py_env

- name: "Install docker-py"
  pip:
    name: docker-py
    state: present
  become: true
  tags:
    - docker_install
    - py_env

- name: debug
  debug:
    msg: "{{ docker_containers_config }}"
  tags:
    - debug

- name: "Start containers"
  docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: "{{ item.state | default('started') }}"
    restart: "{{ item.restart | default('no') }}"
    restart_policy: "{{ item.restart_policy | default('always') }}"
    network_mode: "{{ item.network_mode | default(omit) }}"
    log_driver: "{{ item.log_driver | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    ports: "{{ item.ports | default(omit) }}"
    devices: "{{ item.devices | default(omit) }}"
    links: "{{ item.links | default(omit) }}"
    env: "{{ item.env | default(omit) }}"
    capabilities: "{{ item.capabilities | default(omit) }}"
    security_opts: "{{ item.security_opts | default(omit) }}"
    command: "{{ item.command | default(omit) }}"
  with_items: "{{ docker_containers_config | default([]) }}"
  become: yes
  tags:
    - container_start

- name: "Restart containers"
  docker_container:
    name: "{{ item.restart_docker }}"
    state: "started"
    restart: yes
  with_items: "{{ template_files_config }}"
  when: templates_config.changed
