Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node1|
    config.disksize.size = '10GB'
    #Put here your publik key
    config.vm.provision "shell", inline: <<-SHELL
      echo "ssh-rsa some_publik key" >> /home/vagrant/.ssh/authorized_keys
      SHELL
    node1.vm.box = "debian9.4.box"
    node1.vm.hostname = "devsandbox"
    node1.vm.box_url = "evheniyt/debian9.4"

    node1.vm.network :private_network, ip: "172.28.128.110"
    node1.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"

    node1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2096]
      v.customize ["modifyvm", :id, "--name", "devsandbox1"]
    end
  end
end
